

# Mod Properties
mod_version = 1.0.0
maven_group = com.example.mod
archives_name = example-mod
enabled_platforms = fabric,neoforge

# Minecraft Properties
minecraft_version = 26.1

# Architectury Properties
architectury_api_version = 20.0.2

# Fabric Properties
fabric_loader_version = 0.18.5
fabric_api_version = 0.144.1

# NeoForge Properties
neoforge_version = 26.1.0.1-beta