license = "MIT"
#issueTrackerURL = ""

[[mods]]
modId = "delivery_questing"
version = "${version}"
displayName = "Delivery Questing - Reborn"
authors = "Space_Mex"
credits = "Henkelmax - Orginal Mod Devloper"
# displayURL = ""
# logoFile = "icon.png"
# credits = ""

description = '''

'''

#[[mixins]]
#config = "example-mod.mixins.json"

[[dependencies.delivery_questing]]
modId = "neoforge"
type = "required"
versionRange = "[26.1.0.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.delivery_questing]]
modId = "minecraft"
type = "required"
versionRange = "[26.1,)"
ordering = "NONE"
side = "BOTH"